Add basic_file

diff --git a/.github/workflows/matrix_push.yaml b/.github/workflows/matrix_push.yaml
--- a/.github/workflows/matrix_push.yaml
+++ b/.github/workflows/matrix_push.yaml
@@ -6,17 +6,17 @@ on:
 
 jobs:
 
-  default_matrix:
-    strategy:
-      matrix:
-        os: [macos-latest, windows-latest, ubuntu-latest]
-        version: [12, 14, 16]
-    runs-on: ${{ matrix.os }}
-    steps:
-    - name: echo matrix value
-      run: |
-        echo ${{ matrix.os }}
-        echo ${{ matrix.version }}
+  # default_matrix:
+  #   strategy:
+  #     matrix:
+  #       os: [macos-latest, windows-latest, ubuntu-latest]
+  #       version: [12, 14, 16]
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #   - name: echo matrix value
+  #     run: |
+  #       echo ${{ matrix.os }}
+  #       echo ${{ matrix.version }}
 
   # max_parallel_matrix:
   #   strategy:
@@ -44,23 +44,23 @@ jobs:
   #       echo ${{ matrix.os }}
   #       echo ${{ matrix.version }}
 
-  fail_fast_matrix:
-    strategy:
-      fail-fast: true
-      matrix:
-        os: [macos-latest, windows-latest, ubuntu-latest]
-        version: [12, 14, 16]
-    runs-on: ${{ matrix.os }}
-    steps:
-    - name: echo matrix value
-      run: |
-        echo ${{ matrix.os }}
-        echo ${{ matrix.version }}
-    - name: if failed
-      if: |
-        ${{ matrix.os }} == 'macos-latest' && ${{ matrix.version }} == '12'
-      run: |
-        exit 1
+  # fail_fast_matrix:
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       os: [macos-latest, windows-latest, ubuntu-latest]
+  #       version: [12, 14, 16]
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #   - name: echo matrix value
+  #     run: |
+  #       echo ${{ matrix.os }}
+  #       echo ${{ matrix.version }}
+  #   - name: if failed
+  #     if: |
+  #       ${{ matrix.os }} == 'macos-latest' && ${{ matrix.version }} == '12'
+  #     run: |
+  #       exit 1
 
 
   include_matrix:
@@ -70,7 +70,7 @@ jobs:
         version: [12, 14, 16]
         include:
           - os: windows-latest
-            version: 17
+            version: 12
     runs-on: ${{ matrix.os }}
     steps:
     - name: echo matrix value
@@ -79,17 +79,17 @@ jobs:
         echo ${{ matrix.version }}
 
   
-  exclude_matrix:
-    strategy:
-      matrix:
-        os: [macos-latest, windows-latest, ubuntu-latest]
-        version: [12, 14, 16]
-        exclude:
-          - os: windows-latest
-            version: 17
-    runs-on: ${{ matrix.os }}
-    steps:
-    - name: echo matrix value
-      run: |
-        echo ${{ matrix.os }}
-        echo ${{ matrix.version }}
+  # exclude_matrix:
+  #   strategy:
+  #     matrix:
+  #       os: [macos-latest, windows-latest, ubuntu-latest]
+  #       version: [12, 14, 16]
+  #       exclude:
+  #         - os: windows-latest
+  #           version: 12
+  #   runs-on: ${{ matrix.os }}
+  #   steps:
+  #   - name: echo matrix value
+  #     run: |
+  #       echo ${{ matrix.os }}
+  #       echo ${{ matrix.version }}
